Limit kw_only usage to attrs 18.2 or newer (#292)
Apart from python2, the kw_only keyword argument for `attr.s()` throws
`TypeError: attrs() got an unexpected keyword argument 'kw_only'` also
on python3 installations using version of attrs module older than 18.2.
RHEL-8 ships attrs in version 17.4, hence the argument needs to be
excluded there as well.